# Generated by Django 4.0.5 on 2022-07-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailentry',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='emailentry',
            name='sent_datetime',
        ),
    ]
