# Generated by Django 4.0.5 on 2022-07-13 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0003_emailentry_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='sent_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 12, 23, 35, 617341, tzinfo=utc), verbose_name='Дата и время отправки'),
            preserve_default=False,
        ),
    ]
