# Generated by Django 4.0.5 on 2022-07-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0004_emailentry_sent_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailentry',
            old_name='created_datetime',
            new_name='created_at',
        ),
    ]
