# Generated by Django 4.0.5 on 2022-07-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0005_rename_created_datetime_emailentry_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailentry',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='emailentry',
            name='text',
        ),
    ]
