# Generated by Django 4.0.5 on 2022-07-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Пост в блоге', 'verbose_name_plural': 'Посты в блоге'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='edited_date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения'),
        ),
    ]
