# Generated by Django 4.0.5 on 2022-07-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options_blogpost_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date_time',
            field=models.DateTimeField(verbose_name='Дата и время публикации'),
        ),
    ]
